server:
  port: 8080
  servlet:
    context-path: /identity_service
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: root
jwt:
  signKey: "TiLyhulYNPgfXQU1HDKjDdGqjxxzHT3f9wHGzZ9EXiKb4/skSbk4eywLBKpGXrfk\r"